version: '3.8'

services:
  backend:
    container_name: magical_clarke
    build: ./Backend/chatbot-service
    ports:
      - "8000:8000"
    networks:
      - speak-ez-network

  frontend:
    container_name: loving_newton
    build: ./Frontend/speakez
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - speak-ez-network

networks:
  speak-ez-network:
    driver: bridge